\c testdb testusr

create table book (id integer generated by default as identity, title varchar (255), isbn varchar (255), category_id integer, format_id integer, primary key (id));
create table category_master (id integer generated by default as identity, name varchar (255), primary key (id));
create table format_master (id integer generated by default as identity, name varchar (255), primary key (id));
create table account_master (id integer generated by default as identity, name varchar(255), password varchar(255), authority_id integer, primary key (id));
create table authority_master (id integer generated by default as identity, name varchar(255), primary key (id));

alter table book add constraint book_category_id_fk foreign key (category_id) references category_master;
alter table book add constraint book_format_id_fk foreign key (format_id) references format_master;
alter table account_master add constraint account_authority_id_fk foreign key (authority_id) references authority_master;
