## create-database.sh
#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL  
  CREATE USER testusr PASSWORD 'testusr' CREATEDB;
  CREATE DATABASE testdb OWNER testusr;
  GRANT ALL PRIVILEGES ON DATABASE testdb TO testusr;

  create table ACCOUNT_MASTER(id integer generated by default as identity, name varchar (255), password varchar (255), primary key (id));
  create table ACCOUNT_MASTER_AUTHORITY_MASTER(ACCOUNT_MASTER_id integer not null, authorities_id integer not null);
  create table AUTHORITY_MASTER(id integer generated by default as identity, authority varchar (255), primary key (id));
  create table BOOK(id integer generated by default as identity, isbn varchar (255), title varchar (255), CATEGORY_ID integer, FORMAT_ID integer, primary key (id));
  create table CATEGORY_MASTER(id integer generated by default as identity, name varchar (255), primary key (id));
  create table FORMAT_MASTER(id integer generated by default as identity, name varchar (255), primary key (id));

  alter table ACCOUNT_MASTER_AUTHORITY_MASTER add constraint UK_p5hevk1suyxhwdjkfbo964k63 unique (authorities_id);
  alter table ACCOUNT_MASTER_AUTHORITY_MASTER add constraint FKcwryllprbodmvtrl3ttxfyblc foreign key (authorities_id) references AUTHORITY_MASTER;
  alter table ACCOUNT_MASTER_AUTHORITY_MASTER add constraint FKp4ma8bnxc4ho21qho63kifbv6 foreign key (ACCOUNT_MASTER_id) references ACCOUNT_MASTER;
  alter table BOOK add constraint FKpl6tm7wssv8rcu50kxv7xy6aj foreign key (CATEGORY_ID) references CATEGORY_MASTER;
  alter table BOOK add constraint FK8p0xjh0oro1bd7yf7da51fntn foreign key (FORMAT_ID) references FORMAT_MASTER;

  insert into account_master(id,name,password) values (1,'admin','$2a$10$YRokR.9GIz5vElEobIssWecFfhDJGpXIS1rq.80II8gEAxeS2yfaG');
  insert into authority_master(id,authority) values (1,'ROLE_USER');

  insert into account_master_authority_master(account_master_id,authorities_id) values (1,1);

  insert into category_master(id,name) values (1,'技術書');
  insert into category_master(id,name) values (2,'小説');
  insert into category_master(id,name) values (3,'雑誌');

  insert into format_master(id,name) values (1,'書籍');
  insert into format_master(id,name) values (2,'電子書籍');
EOSQL
